import 'server-only';

import type { Listing } from '@/types';

/**
 * Nguồn dữ liệu tin đăng.
 *
 * ⚠️ TOÀN BỘ LÀ DỮ LIỆU DEMO lấy từ bản thiết kế — giá, diện tích, số phòng
 * đều là số minh hoạ. Thay bằng dữ liệu thật (hoặc nối DB) trước khi chạy
 * production; đặc biệt không để giá chưa kiểm chứng lên trang.
 *
 * Đây là seam để sau này đổi sang DB thật: giữ nguyên chữ ký hàm bất đồng bộ
 * bên dưới, chỉ thay phần thân.
 */
const LISTINGS: readonly Listing[] = [
  {
    slug: 'ocean-estate-villa',
    title: 'Ocean Estate Villa',
    location: 'Hoa Hai · Ngu Hanh Son',
    listingType: 'sale',
    price: '$3,596,000',
    beds: 3,
    baths: 3,
    area: '917 m²',
    badge: 'Signature listing',
    badgeTone: 'gold',
    image: '/images/listings/ocean-estate-villa.webp',
    imageAlt: 'Ocean Estate Villa living room',
  },
  {
    slug: 'riverfront-penthouse',
    title: 'The Riverfront Penthouse',
    location: 'Hai Chau · Han River',
    listingType: 'sale',
    price: '$1,280,000',
    beds: 4,
    baths: 4,
    area: '318 m²',
    badge: 'New release',
    badgeTone: 'navy',
    image: '/images/listings/riverfront-penthouse.webp',
    imageAlt: 'Riverfront penthouse living room',
  },
  {
    slug: 'son-tra-sky-residence',
    title: 'Son Tra Sky Residence',
    location: 'Son Tra · My Khe',
    listingType: 'sale',
    price: '$685,000',
    beds: 3,
    baths: 3,
    area: '186 m²',
    badge: 'Sea view',
    badgeTone: 'navy',
    image: '/images/listings/son-tra-sky-residence.webp',
    imageAlt: 'Son Tra Sky Residence interior',
  },
  {
    slug: 'an-thuong-design-apartment',
    title: 'An Thuong Design Apartment',
    location: 'My An · An Thuong',
    listingType: 'sale',
    price: '$425,000',
    beds: 2,
    baths: 2,
    area: '128 m²',
    badge: 'Turn-key',
    badgeTone: 'navy',
    image: '/images/listings/an-thuong-design-apartment.webp',
    imageAlt: 'An Thuong Design Apartment interior',
  },
  {
    slug: 'marina-garden-residence',
    title: 'Marina Garden Residence',
    location: 'Son Tra · Marina',
    listingType: 'sale',
    price: '$790,000',
    beds: 3,
    baths: 3,
    area: '204 m²',
    badge: 'Private garden',
    badgeTone: 'navy',
    image: '/images/listings/marina-garden-residence.webp',
    imageAlt: 'Marina Garden Residence interior',
  },
  {
    slug: 'my-khe-coastal-apartment',
    title: 'My Khe Coastal Apartment',
    location: 'Son Tra · My Khe',
    listingType: 'rent',
    price: '$2,250',
    priceNote: '/ month',
    beds: 2,
    baths: 2,
    area: '118 m²',
    badge: 'Most requested',
    badgeTone: 'gold',
    image: '/images/listings/my-khe-coastal-apartment.webp',
    imageAlt: 'My Khe Coastal Apartment interior',
  },
  {
    slug: 'han-river-executive-home',
    title: 'Han River Executive Home',
    location: 'Hai Chau · City Centre',
    listingType: 'rent',
    price: '$1,850',
    priceNote: '/ month',
    beds: 2,
    baths: 2,
    area: '105 m²',
    badge: 'City living',
    badgeTone: 'navy',
    image: '/images/listings/han-river-executive-home.webp',
    imageAlt: 'Han River Executive Home interior',
  },
  {
    slug: 'an-thuong-urban-loft',
    title: 'An Thuong Urban Loft',
    location: 'My An · An Thuong',
    listingType: 'rent',
    price: '$1,450',
    priceNote: '/ month',
    beds: 1,
    baths: 1,
    area: '78 m²',
    badge: 'Walkable',
    badgeTone: 'navy',
    image: '/images/listings/an-thuong-urban-loft.webp',
    imageAlt: 'An Thuong Urban Loft interior',
  },
  {
    slug: 'ocean-villas-family-residence',
    title: 'Ocean Villas Family Residence',
    location: 'Hoa Hai · Beachfront',
    listingType: 'rent',
    price: '$3,900',
    priceNote: '/ month',
    beds: 3,
    baths: 3,
    area: '280 m²',
    badge: 'Private villa',
    badgeTone: 'gold',
    image: '/images/listings/ocean-villas-family-residence.webp',
    imageAlt: 'Ocean Villas Family Residence interior',
  },
  {
    slug: 'marina-two-bed-residence',
    title: 'Marina Two-Bed Residence',
    location: 'Son Tra · Han River',
    listingType: 'rent',
    price: '$1,700',
    priceNote: '/ month',
    beds: 2,
    baths: 2,
    area: '96 m²',
    badge: 'Available now',
    badgeTone: 'navy',
    image: '/images/listings/marina-two-bed-residence.webp',
    imageAlt: 'Marina Two-Bed Residence bedroom',
  },
  {
    slug: 'son-tra-quiet-retreat',
    title: 'Son Tra Quiet Retreat',
    location: 'Son Tra · Riverside',
    listingType: 'rent',
    price: '$1,950',
    priceNote: '/ month',
    beds: 2,
    baths: 2,
    area: '112 m²',
    badge: 'Quiet location',
    badgeTone: 'navy',
    image: '/images/listings/son-tra-quiet-retreat.webp',
    imageAlt: 'Son Tra Quiet Retreat bedroom',
  },
];

export async function getListingsByType(listingType: Listing['listingType']): Promise<Listing[]> {
  return LISTINGS.filter((listing) => listing.listingType === listingType);
}
